AWSTemplateFormatVersion: "2010-09-09"
Description: Provision ALB & EC2 & RDS

Parameters: 
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: marube23

  MyIP:
    Description: IP address allowed to access EC2
    Type: String
    Default: 61.44.234.6/32

  DatabaseMasterName:
    Description: Database Master User Name
    Type : String
    Default: root

  DatabaseMasterPassword:
    Description: Database Master User Password
    Type: String
    NoEcho: true
    Default: 48694062

  DatabaseName:
    Description: Database Name
    Type : String
    Default: awsstudy

Resources:
  # ------------------------------------------------------------#
  #  VPC
  # ------------------------------------------------------------#
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: aws-study-cfnvpc

  # ------------------------------------------------------------#
  #  Internet Gateway
  # ------------------------------------------------------------#        
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: aws-study-cfnigw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW        

  # ------------------------------------------------------------#
  #  Route Table
  # ------------------------------------------------------------#    
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: aws-study-cfnrtb

  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  # ------------------------------------------------------------#
  #  Public Sunbet A
  # ------------------------------------------------------------#
  PubSubA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: aws-study-cfnpubsub-A

  AssoPubSubRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSubA
      RouteTableId: !Ref RouteTable

  # ------------------------------------------------------------#
  #  Private Sunbet A
  # ------------------------------------------------------------#
  PriSubA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: aws-study-cfnprisub-A

  # ------------------------------------------------------------#
  #  Public Sunbet C
  # ------------------------------------------------------------#
  PubSubC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: aws-study-cfnpubsub-C

  # ------------------------------------------------------------#
  #  Private Sunbet C
  # ------------------------------------------------------------#
  PriSubC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: 10.0.4.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: aws-study-cfnprisub-C 

  # ------------------------------------------------------------#
  #  ALB Security Group
  # ------------------------------------------------------------#
  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: aws-study-cfnalbsg
      GroupDescription: Allow HTTP access from internet
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # http  
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: aws-study-cfnalbsg

  # ------------------------------------------------------------#
  #  ALB
  # ------------------------------------------------------------#
  ALB:
    Type : AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: aws-study-cfnalb
      Scheme: "internet-facing"
      SecurityGroups:
        - !Ref ALBSG
      # At least two subnet is needed
      Subnets:
        - !Ref PubSubA
        - !Ref PubSubC
      Tags:
        - Key: Name
          Value: aws-study-cfnalb

  # ------------------------------------------------------------#
  #  Target Group
  # ------------------------------------------------------------#
  ALBTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # Health check enabled must be true for target groups with target type 'instance' 
      TargetType: instance
      Protocol: HTTP
      HealthCheckPath: /
      HealthCheckEnabled: True
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Name: aws-study-cfntg
      VpcId: !Ref VPC
      Port: 8080
      Matcher:
        HttpCode: 200,300,301
      Targets:
        # If the target type is instance, you cannot override the Availability Zone
        - Id: !Ref EC2
          Port: 8080
        - Id: !Ref EC2
          Port: 80  
      Tags:
        - Key: Name
          Value: aws-study-cfntg        

  # ------------------------------------------------------------#
  #  ALB Listner
  # ------------------------------------------------------------#
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref ALBTG
          Type: forward
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  # ------------------------------------------------------------#
  #  EC2 Security Group
  # ------------------------------------------------------------#  
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP and Springboot from Internet
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # SSH
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
        # http 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        # Springboot and only access from ALB
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ALBSG
      Tags:
        - Key: Name
          Value: aws-study-cfnec2sg  
  
  # ------------------------------------------------------------#
  #  EC2
  # ------------------------------------------------------------#
  EC2: 
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      InstanceType: t2.micro
      ImageId: ami-070d2b24928913a49
      KeyName: !Ref KeyName
      VpcId: !Ref VPC
      # 削除保護
      DisableApiTermination: false
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref PubSubA
          GroupSet:
            - !Ref EC2SG
      Tags:
        - Key: Name
          Value: aws-study-cfnec2

  # ------------------------------------------------------------#
  #  Database Subnet Group
  # ------------------------------------------------------------#
  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: aws-study-cfndbsg
      DBSubnetGroupName: aws-study-cfndbsg
      SubnetIds:
        - !Ref PriSubA
        - !Ref PriSubC
      Tags:
        - Key: Name
          Value: aws-study-cfndbsg

  # ------------------------------------------------------------#
  #  RDS Security Group
  # ------------------------------------------------------------#
  RDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: aws-study-cfnrdssg
      GroupDescription: Allow Request from WebServer
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # https and only access from EC2
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SG
      Tags:
        - Key: Name
          Value: aws-study-cfnrdssg

  # ------------------------------------------------------------#
  #  RDS
  # ------------------------------------------------------------#
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      EngineVersion: 8.0.41
      # シングルAZ
      MultiAZ: false
      DBInstanceIdentifier: aws-study-cfnrds
      MasterUsername: !Ref DatabaseMasterName
      MasterUserPassword: !Ref DatabaseMasterPassword
      DBInstanceClass: db.t4g.micro
      StorageType: gp2
      # ストレージ割り当て
      AllocatedStorage: 20
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      # パブリック接続不許可
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref RDSSG  
      AvailabilityZone: !Select [0, !GetAZs '']
      DBName: !Ref DatabaseName
      # 自動バックアップ保有期間
      BackupRetentionPeriod: 1
      # DB暗号化
      StorageEncrypted: true
      # CloudWatch Logsへのログの有効化
      EnableCloudwatchLogsExports:
        - audit
        - error
        - general
        - slowquery
      # メジャーバージョンアップグレードを許可
      AllowMajorVersionUpgrade: false
      # マイナーバージョン自動アップグレードの有効化
      AutoMinorVersionUpgrade: true
      # 削除時の自動バックアップ同時削除許可
      DeleteAutomatedBackups: true
      # 削除保護
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: aws-study-cfnrds
      

  