AWSTemplateFormatVersion: "2010-09-09"
Description: Watch EC2 instance CPUUtilization and connect WAF For ALB

Outputs:
  ALBDNSName:
    Description: ALB DNS Name
    Value: !GetAtt ALB.DNSName

  WebACLArn:
    Description: WAF WebACL ARN
    Value: !GetAtt WebACL.Arn

  WAFLogGroupArn:
    Description: WAF LogGroup ARN
    Value: !GetAtt WAFLogGroup.Arn

  SNSTopicArn:
    Description: SNS Topic ARN
    Value: !Ref SNSTopic  

Parameters: 
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: marube23

  MyEmail:
    Description: Email address from SNS Topic
    Type: String

  BlockIPAddresses:
    Description: "Blacklist for Blocking IP adress"
    Type: CommaDelimitedList
    Default: 61.44.234.6/32

Resources:
  # ------------------------------------------------------------#
  #  VPC
  # ------------------------------------------------------------#
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: aws-study-cfnvpc

  # ------------------------------------------------------------#
  #  Internet Gateway
  # ------------------------------------------------------------#        
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: aws-study-cfnigw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW        

  # ------------------------------------------------------------#
  #  Route Table
  # ------------------------------------------------------------#    
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: aws-study-cfnrtb

  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  # ------------------------------------------------------------#
  #  Public Sunbet A
  # ------------------------------------------------------------#
  PubSubA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: aws-study-cfnpubsub-A

  AssoPubSubRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSubA
      RouteTableId: !Ref RouteTable

  # ------------------------------------------------------------#
  #  Private Sunbet A
  # ------------------------------------------------------------#
  PriSubA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: aws-study-cfnprisub-A

  # ------------------------------------------------------------#
  #  Public Sunbet C
  # ------------------------------------------------------------#
  PubSubC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: aws-study-cfnpubsub-C

  # ------------------------------------------------------------#
  #  Private Sunbet C
  # ------------------------------------------------------------#
  PriSubC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: 10.0.4.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: aws-study-cfnprisub-C 

  # ------------------------------------------------------------#
  #  ALB Security Group
  # ------------------------------------------------------------#
  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: aws-study-cfnalbsg
      GroupDescription: Allow HTTP access from internet
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # http  
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: aws-study-cfnalbsg

  # ------------------------------------------------------------#
  #  ALB
  # ------------------------------------------------------------#
  ALB:
    Type : AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: aws-study-cfnalb
      Scheme: "internet-facing"
      SecurityGroups:
        - !Ref ALBSG
      # At least two subnet is needed
      Subnets:
        - !Ref PubSubA
        - !Ref PubSubC
      Tags:
        - Key: Name
          Value: aws-study-cfnalb

  # ------------------------------------------------------------#
  #  Target Group
  # ------------------------------------------------------------#
  ALBTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # Health check enabled must be true for target groups with target type 'instance' 
      TargetType: instance
      Protocol: HTTP
      HealthCheckPath: /
      HealthCheckEnabled: True
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Name: aws-study-cfntg
      VpcId: !Ref VPC
      Port: 80
      Matcher:
        HttpCode: 200,300,301
      Targets:
        # If the target type is instance, you cannot override the Availability Zone
        - Id: !Ref EC2
          Port: 80
      Tags:
        - Key: Name
          Value: aws-study-cfntg        

  # ------------------------------------------------------------#
  #  ALB Listner
  # ------------------------------------------------------------#
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref ALBTG
          Type: forward
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  # ------------------------------------------------------------#
  #  EC2 Security Group
  # ------------------------------------------------------------#  
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and only access from ALB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # HTTP and only access from ALB
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSG
      Tags:
        - Key: Name
          Value: aws-study-cfnec2sg  
  
  # ------------------------------------------------------------#
  #  EC2
  # ------------------------------------------------------------#
  EC2: 
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      InstanceType: t2.micro
      ImageId: ami-070d2b24928913a49
      KeyName: !Ref KeyName
      # 削除保護
      DisableApiTermination: false
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          SubnetId: !Ref PriSubA
          GroupSet:
            - !Ref EC2SG
      Tags:
        - Key: Name
          Value: aws-study-cfnec2

  # ------------------------------------------------------------#
  #  CloudWatch Alarm
  # ------------------------------------------------------------#        
  EC2CPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ### 基本設定
      AlarmName: aws-study-cfn-cpu-utilization-alarm
      AlarmDescription: "aws-study-cfnec2 の 60 秒間の 平均 CPU使用率が 0.1 %以上になりました。 SNSに通知します"

      ### メトリクス
      Namespace: "AWS/EC2"
      Dimensions:
        - Name: "InstanceId"
          Value: !Ref EC2
      MetricName: "CPUUtilization"
      Unit: "Percent"

      ### 統計
      Period: 60
      Statistic: "Average"

      ### 評価
      Threshold: 0.1
      # 比較に用いる算術演算
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      # 評価する期間の数
      EvaluationPeriods: 1
      # 「しきい値超過」の数
      DatapointsToAlarm: 1
      TreatMissingData: "missing"

      ### アクション
      ActionsEnabled: True
      AlarmActions:
        - !Ref SNSTopic

  # ------------------------------------------------------------#
  #  Amazon SNS Topic
  # ------------------------------------------------------------# 
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: aws-study-cfn-topic
      Tags:
        - Key: Name
          Value: aws-study-cfn-topic

  # ------------------------------------------------------------#
  #  E-mail Subscription
  # ------------------------------------------------------------#         

  AlarmEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: email
      Endpoint: !Ref MyEmail     

  # ------------------------------------------------------------#
  #  AWS WAF v2
  # ------------------------------------------------------------# 
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: aws-study-cfnalb-waf
      DefaultAction:
        Allow: {}
      Scope: REGIONAL
      Description: "Web ACL for InternetALB"
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: aws-study-cfnalb-waf
        SampledRequestsEnabled: true
      Rules:
        ## 指定したIPアドレスからのアクセスをブロックする
        - Name: IPAddressBlacklistRule
          Priority: 1
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt IPBlacklist.Arn
          Action:
            Block: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: IPAddressBlacklistRule
            SampledRequestsEnabled: true

  # ------------------------------------------------------------#
  # Block IP Address
  # ------------------------------------------------------------# 
  IPBlacklist:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: IPAddressBlacklist
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: !Ref BlockIPAddresses

  # ------------------------------------------------------------# 
  # WebACLAssociation
  # ------------------------------------------------------------# 
  ## WAF と ALB を連携する設定。
  ## WAF と CloudFront 連携時は不要。
  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Ref ALB
      WebACLArn: !GetAtt WebACL.Arn    

  # ------------------------------------------------------------# 
  # WAFv2 Log Config
  # ------------------------------------------------------------# 
  WAFLogsConfig:
    DependsOn: WebACLAssociation
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      # ログデータの送信先
      LogDestinationConfigs:
        - !GetAtt WAFLogGroup.Arn
      # ログデータを出力するWAFのARN
      ResourceArn: !GetAtt WebACL.Arn

  # ------------------------------------------------------------# 
  # CloudWatch Logs Log Group (WAFv2)
  # ------------------------------------------------------------# 
  WAFLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      # aws-waf-logs-から始まる名前にすること。
      LogGroupName: aws-waf-logs-study-cfnalb
      # ログ保存期間
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: aws-waf-logs-study-cfnalb

  # ------------------------------------------------------------# 
  # CloudWatch Logs Resource Policy
  # ------------------------------------------------------------#   
  WAFLogResourcePolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: WAFLogPolicy
      ## CloudWatch Logs に自分のアカウントの WAF サービスに対して 
      ## WAFLogGroup の全ログストリームの作成とログ書き込みを
      ## 許可するリソースベースポリシーを付与する。
      PolicyDocument:
        Fn::Sub:
          - |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "AWSWAFLogs",
                  "Effect": "Allow",
                  "Principal": {
                    "Service": "delivery.logs.amazonaws.com"
                  },
                  "Action": [
                    "logs:CreateLogStream",
                    "logs:PutLogEvents"
                  ],
                  "Resource": "${CloudWatchLogsLogGroupArn}",
                  "Condition": {
                    "StringEquals": {
                      "aws:SourceAccount": ${AWS::AccountId}
                    },
                    "ArnLike": {
                      "aws:SourceArn": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
                    }
                  }
                }
              ]
            }
          - CloudWatchLogsLogGroupArn: !GetAtt WAFLogGroup.Arn       