- hosts: web
  become: true

  vars:
    app_dir: /home/ec2-user/app
    repo_url: https://github.com/koujienami/aws-study.git
    rds_endpoint: "{{ lookup('env', 'RDS_ENDPOINT') }}"
    db_username: "{{ lookup('env', 'DATABASE_MASTER_NAME') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"

  tasks:
    - name: Install Java 21
      dnf:
        name: java-21-amazon-corretto-devel.x86_64
        state: present

    - name: Install git packages
      dnf:
        name:
          - git
        state: present

    - name: Install MySQL repo
      dnf:
        name: https://dev.mysql.com/get/mysql84-community-release-el9-1.noarch.rpm
        state: present

    - name: Install MySQL client
      dnf:
        name:
          - mysql
          - mysql-community-client
        state: present    

    # アプリケーションインストール
    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    # application.properties を templates に書き換え
    - name: Replace application.properties
      template:
        src: templates/application.properties.j2
        dest: "{{ app_dir }}/src/main/resources/application.properties"
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    # データベース内に必要な値を入力
    - name: Initialize database
      shell: |
        mysql -h {{ rds_endpoint }} -u {{ db_username }} <<EOF
        CREATE DATABASE IF NOT EXISTS awsstudy;
        USE awsstudy;

        CREATE TABLE IF NOT EXISTS student (
          id INT PRIMARY KEY AUTO_INCREMENT,
          name VARCHAR(255) NOT NULL
        );

        INSERT INTO student (name)
        SELECT 'Kouji Enami'
        WHERE NOT EXISTS (
          SELECT * FROM student WHERE name='Kouji Enami'
        );
        EOF
      environment:
        MYSQL_PWD: "{{ db_password }}"

    # 必要な権限を付与
    - name: Make gradlew executable
      file:
        path: "{{ app_dir }}/gradlew"
        mode: '0755'

    - name: Build with Gradle
      command: ./gradlew build
      args:
        chdir: "{{ app_dir }}"
    
    # Springboot 起動
    - name: Run Spring Boot
      shell: |
        nohup java -jar build/libs/*.jar > app.log 2>&1 &
      args:
        chdir: "{{ app_dir }}"
